<a href="https://colab.research.google.com/github/shivammehta007/QuestionGenerator/blob/master/Generation_of_Blanks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fill in the blank Generator With Neural Networks

## Download Code from Github

In [1]:
!rm -rf QuestionGenerator
import os
from getpass import getpass
import urllib
import subprocess

user = input('User name: ')
password = getpass('Password: ')
password = urllib.parse.quote(password) # your password is converted into url format
# repo_name = input('Repo name: ')

cmd_string = 'git clone --single-branch --branch master  https://{0}:{1}@github.com/{0}/{2}.git'.format(user, password, 'QuestionGenerator')
stdout = subprocess.Popen(cmd_string, shell=True, stdout=subprocess.PIPE)
print(stdout.communicate()[0])
cmd_string, password = "", "" # removing the password from the variable

User name: shivammehta007
Password: ··········
b''


In [2]:
!rm -rf QuestionGenerator/FromScratch
!rm -rf QuestionGenerator/classifier
%cd QuestionGenerator/FITBGenerator/

/content/QuestionGenerator/FITBGenerator


In [3]:
%ls

config/  datasetloader.py    lossfunction.py  preprocessdata.py  utility.py
data/    helperfunctions.py  model/           train.py


## Download Glove from Kaggle

In [0]:
import os
import json

kaggle_info = json.load(open("/content/drive/My Drive/kaggle.json"))
os.environ['KAGGLE_USERNAME'] = kaggle_info["username"]
os.environ['KAGGLE_KEY'] = kaggle_info["key"]

In [5]:
!kaggle datasets list --user thanakomsn

ref                        title               size  lastUpdated          downloadCount  
-------------------------  -----------------  -----  -------------------  -------------  
thanakomsn/glove6b300dtxt  glove.6B.300d.txt  386MB  2017-11-28 07:19:43           2744  


In [6]:
!kaggle datasets download thanakomsn/glove6b300dtxt 

 98% 377M/386M [00:06<00:00, 82.0MB/s]
100% 386M/386M [00:06<00:00, 61.9MB/s]


In [0]:
%mkdir .vector_cache
%mv glove6b300dtxt.zip .vector_cache/

In [8]:
!unzip .vector_cache/glove6b300dtxt.zip
%ls -a .vector_cache/

Archive:  .vector_cache/glove6b300dtxt.zip
  inflating: glove.6B.300d.txt       
./  ../  glove6b300dtxt.zip


## Preprocessing Dataset

In [0]:
# !python preprocessdata.py

## Training

In [21]:
!python train.py -n 50

[DEBUG | train.py:221 -             <module>() ] Namespace(batch_size=64, bidirectional=True, dropout=0.7, embedding_dim=300, epochs=50, freeze_embeddings=1, hidden_dim=128, l2_regularization=0.001, learning_rate=0.001, linear_hidden_dim=128, model='RNNHiddenClassifier', model_location=None, n_layers=1, seed=1234)
[DEBUG | train.py:222 -             <module>() ] Custom seed set with: 1234
[INFO | train.py:224 -             <module>() ] Loading Dataset
[DEBUG | datasetloader.py:74 -        get_iterators() ] Data Loaded Successfully!
[INFO | vocab.py:386 -                cache() ] Loading vectors from .vector_cache/glove.6B.300d.txt.pt
[DEBUG | datasetloader.py:85 -        get_iterators() ] Vocabulary Loaded
[DEBUG | datasetloader.py:94 -        get_iterators() ] Created Iterators
[INFO | train.py:228 -             <module>() ] Dataset Loaded Successfully
[DEBUG | train.py:66 - initialize_new_model() ] Initializing Model
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py:50: 

## Editor

### RNN Classifier

In [31]:
%%writefile model/RNNClassifiers.py
"""
Model Architectures of RNN based Classifiers
"""

import logging

import torch
import torch.nn as nn

from config.root import LOGGING_FORMAT, LOGGING_LEVEL

# Initialize logger for this file
logger = logging.getLogger(__name__)
logging.basicConfig(level=LOGGING_LEVEL, format=LOGGING_FORMAT)


class LSTMWithPackPaddedSequences(nn.Module):
    def __init__(self, embedding_dim, hidden_dim, num_layers, bidirectional, dropout):

        super().__init__()

        self.rnn = nn.LSTM(
            embedding_dim,
            hidden_dim,
            num_layers=num_layers,
            bidirectional=bidirectional,
            dropout=dropout,
        )

    def forward(self, embedded, text_lengths):

        embedded = embedded.permute(1, 0, 2)

        packed_embedded = nn.utils.rnn.pack_padded_sequence(embedded, text_lengths)

        packed_output, (hidden, _) = self.rnn(packed_embedded)

        output, output_lengths = nn.utils.rnn.pad_packed_sequence(packed_output)

        output = output.permute(1, 0, 2)

        return output, output_lengths, hidden


class RNNHiddenClassifier(nn.Module):
    """
    This classifier concatenates the last hidden
    """

    def __init__(
        self,
        vocab_size,
        embedding_dim,
        hidden_dim,
        output_dim,
        n_layers,
        bidirectional,
        dropout,
        pad_idx,
    ):

        super().__init__()

        self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx=pad_idx)

        self.bidirectional = bidirectional

        self.rnn = LSTMWithPackPaddedSequences(
            embedding_dim,
            hidden_dim,
            num_layers=n_layers,
            bidirectional=bidirectional,
            dropout=dropout,
        )

        if bidirectional:
            self.fc = nn.Linear(2 * hidden_dim, output_dim)
        else:
            self.fc = nn.Linear(hidden_dim, output_dim)

        self.dropout = nn.Dropout(dropout)

    def forward(self, text, text_lengths):

        embedded = self.dropout(self.embedding(text))

        output, output_lengths, hidden = self.rnn(embedded, text_lengths)

        output = self.fc(output)

        return output


Overwriting model/RNNClassifiers.py


### HelperFunctions

In [20]:
%%writefile helperfunctions.py
"""
Helper Functions containing training and evaluation methods
"""

import torch
import torch.nn.functional as F
import numpy as np
from tqdm.auto import tqdm
from utility import categorical_accuracy, binary_accuracy
from config.root import device


def train(model, iterator, optimizer, criterion):

    epoch_loss = 0
    epoch_acc = 0

    model.train()

    for batch in tqdm(iterator, total=len(iterator)):

        optimizer.zero_grad()

        text, text_lengths = batch.answer
        max_len = text.shape[1]

        predictions = model(text, text_lengths)

        mask, key = get_mask_key_from_batch(batch, text, max_len, text_lengths)

        loss = criterion(predictions, key, mask)

        acc = binary_accuracy(predictions, predictions, mask)

        loss.backward()

        optimizer.step()

        epoch_loss += loss.item()
        epoch_acc += acc.item()

    return epoch_loss / len(iterator), epoch_acc / len(iterator)


def get_mask_key_from_batch(batch, text, max_len, text_lengths):
    key, _ = batch.key

    key = (
        torch.from_numpy(np.where(np.isin(text.cpu().numpy(), key.cpu().numpy()), 1, 0))
        .float()
        .to(device)
        .unsqueeze(2)
    )

    mask = (
        (
            torch.arange(max_len, device=device).expand(len(text_lengths), max_len)
            < text_lengths.unsqueeze(1)
        )
        .float()
        .unsqueeze(2)
    )
    return mask, key


def evaluate(model, iterator, criterion):
    epoch_loss = 0
    epoch_acc = 0

    model.eval()

    with torch.no_grad():

        for batch in tqdm(iterator, total=len(iterator)):

            text, text_lengths = batch.answer
            max_len = text.shape[1]
            predictions = model(text, text_lengths)

            mask, key = get_mask_key_from_batch(batch, text, max_len, text_lengths)

            loss = criterion(predictions, key, mask)

            acc = binary_accuracy(predictions, key, mask)

            epoch_loss += loss.item()
            epoch_acc += acc.item()

    return epoch_loss / len(iterator), epoch_acc / len(iterator)


Overwriting helperfunctions.py


### DatasetLoader

In [43]:
%%writefile datasetloader.py
"""
Load Dataset
"""

import logging
import os

import pandas as pd
import torch
from torchtext import data, datasets

from config.data import (
    DATASET_FOLDER,
    PROCESSED_DATASET,
    PROCESSED_DATASET_FOLDER,
    PROCESSED_DATASET_TRAIN_FILENAME,
    PROCESSED_DATASET_TEST_FILENAME,
    TEMP_DIR,
)
from config.hyperparameters import BATCH_SIZE, MAX_VOCAB
from config.root import LOGGING_FORMAT, LOGGING_LEVEL, device
from utility import tokenizer

# Initialize logger for this file
logger = logging.getLogger(__name__)
logging.basicConfig(level=LOGGING_LEVEL, format=LOGGING_FORMAT)


class GrammarDasetAnswerKey:
    def __init__(self):

        self.dataset_location = PROCESSED_DATASET

        self.answer = data.Field(
            tokenize=tokenizer, include_lengths=True, batch_first=True
        )
        self.key = data.Field(
            tokenize=tokenizer, include_lengths=True, batch_first=True
        )

        self.fields = None
        self.trainset = None
        self.testset = None
        self.train_iterator, self.test_iterator = None, None

    @classmethod
    def get_iterators(cls, batch_size):
        """
        Load dataset and return iterators
        """
        grammar_dataset = cls()

        grammar_dataset.fields = [
            ("answer", grammar_dataset.answer),
            ("key", grammar_dataset.key),
        ]

        if not os.path.exists(PROCESSED_DATASET["train"]) or not os.path.exists(
            PROCESSED_DATASET["test"]
        ):
            raise FileNotFoundError(
                "Please run the preprocessdata.py first by executing python preprocessdata.py"
            )

        grammar_dataset.trainset, grammar_dataset.testset = data.TabularDataset.splits(
            path=os.path.join(DATASET_FOLDER, PROCESSED_DATASET_FOLDER),
            train=PROCESSED_DATASET_TRAIN_FILENAME,
            test=PROCESSED_DATASET_TEST_FILENAME,
            format="tsv",
            fields=grammar_dataset.fields,
            skip_header=True,
        )

        logger.debug("Data Loaded Successfully!")

        grammar_dataset.answer.build_vocab(
            grammar_dataset.trainset,
            max_size=MAX_VOCAB,
            vectors="glove.6B.300d",
            unk_init=torch.Tensor.normal_,
        )

        grammar_dataset.key.vocab = grammar_dataset.answer.vocab

        logger.debug("Vocabulary Loaded")

        grammar_dataset.train_iterator, grammar_dataset.test_iterator = data.BucketIterator.splits(
            (grammar_dataset.trainset, grammar_dataset.testset),
            batch_size=batch_size,
            sort_within_batch=True,
            sort_key=lambda x: len(x.answer),
            device=device,
        )
        logger.debug("Created Iterators")

        return grammar_dataset


Overwriting datasetloader.py


### Train.py

In [12]:
%%writefile train.py
"""
Training script for the model
"""
import argparse
import logging
import os
import time

import torch
import torch.nn as nn
import torch.optim as optim
from tqdm.auto import tqdm

from config.hyperparameters import (
    BATCH_SIZE,
    BIDIRECTION,
    DROPOUT,
    EMBEDDING_DIM,
    EPOCHS,
    FREEZE_EMBEDDINGS,
    HIDDEN_DIM,
    LR,
    N_LAYERS,
    WEIGHT_DECAY,
    CNN_N_FILTER,
    CNN_FILTER_SIZES,
    LINEAR_HIDDEN_DIM,
)
from config.root import (
    LOGGING_FORMAT,
    LOGGING_LEVEL,
    TRAINED_CLASSIFIER_FOLDER,
    TRAINED_CLASSIFIER_RNNHIDDEN,
    device,
    seed_all,
    SEED,
)
from datasetloader import GrammarDasetAnswerKey
from helperfunctions import evaluate, train
from model import RNNHiddenClassifier
from utility import categorical_accuracy, epoch_time

# Initialize logger for this file
logger = logging.getLogger(__name__)
logging.basicConfig(level=LOGGING_LEVEL, format=LOGGING_FORMAT)


def count_parameters(model):
    """Method to count the number of parameters"""
    return sum(p.numel() for p in model.parameters() if p.requires_grad)


def initialize_new_model(
    classifier_type,
    dataset,
    embedding_dim,
    hidden_dim,
    n_layers,
    bidirectional,
    dropout,
    freeze_embeddings,
    linear_hidden_dim,
):
    """Method to initialise new model, takes in dataset object and hyperparameters as parameter"""
    logger.debug("Initializing Model")
    VOCAB_SIZE = len(dataset.answer.vocab)
    PAD_IDX = dataset.answer.vocab.stoi[dataset.answer.pad_token]
    pretrained_embeddings = dataset.answer.vocab.vectors
    UNK_IDX = dataset.answer.vocab.stoi[dataset.answer.unk_token]
    OUTPUT_LAYERS = 1
    if classifier_type == "RNNHiddenClassifier":

        model = RNNHiddenClassifier(
            VOCAB_SIZE,
            embedding_dim,
            hidden_dim,
            OUTPUT_LAYERS,
            n_layers,
            bidirectional,
            dropout,
            PAD_IDX,
        )
    else:
        raise TypeError("Invalid Classifier selected")

    if freeze_embeddings:
        model.embedding.weight.requires_grad = False

    logger.debug(
        "Freeze Embeddings Value {}: {}".format(
            freeze_embeddings, model.embedding.weight.requires_grad
        )
    )

    logger.info(
        "Model Initialized with {:,} trainiable parameters".format(
            count_parameters(model)
        )
    )

    # Initialize pretrained word embeddings

    model.embedding.weight.data.copy_(pretrained_embeddings)

    # Initialize Padding and Unknown as 0
    model.embedding.weight.data[UNK_IDX] = torch.zeros(embedding_dim)
    model.embedding.weight.data[PAD_IDX] = torch.zeros(embedding_dim)

    logger.debug("Copied PreTrained Embeddings")
    return model


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="Utility to train the Model")

    parser.add_argument(
        "-s",
        "--seed",
        default=SEED,
        help="Set custom seed for reproducibility",
        type=int,
    )

    parser.add_argument(
        "-loc",
        "--model-location",
        default=None,
        help="Give an already trained model location to use and train more epochs on it",
    )

    parser.add_argument(
        "-b",
        "--bidirectional",
        default=BIDIRECTION,
        help="Makes the model Bidirectional",
        type=bool,
    )
    parser.add_argument(
        "-d",
        "--dropout",
        default=DROPOUT,
        help="Dropout count for the model",
        type=float,
    )
    parser.add_argument(
        "-e",
        "--embedding-dim",
        default=EMBEDDING_DIM,
        help="Embedding Dimensions",
        type=int,
    )
    parser.add_argument(
        "-hd",
        "--hidden-dim",
        default=HIDDEN_DIM,
        help="Hidden dimensions of the RNN",
        type=int,
    )
    parser.add_argument(
        "-l", "--n-layers", default=N_LAYERS, help="Number of layers in RNN", type=int
    )
    parser.add_argument(
        "-lr",
        "--learning-rate",
        default=LR,
        help="Learning rate of Adam Optimizer",
        type=float,
    )
    parser.add_argument(
        "-n",
        "--epochs",
        default=EPOCHS,
        help="Number of Epochs to train model",
        type=int,
    )
    parser.add_argument(
        "-batch",
        "--batch_size",
        default=BATCH_SIZE,
        help="Number of Epochs to train model",
        type=int,
    )

    parser.add_argument(
        "-f",
        "--freeze-embeddings",
        default=FREEZE_EMBEDDINGS,
        help="Freeze Embeddings of Model",
        type=int,
    )

    parser.add_argument(
        "-l2",
        "--l2-regularization",
        default=WEIGHT_DECAY,
        help="Value of alpha in l2 regularization 0 means no regularization ",
        type=float,
    )

    parser.add_argument(
        "-m",
        "--model",
        default="RNNHiddenClassifier",
        choices=["RNNHiddenClassifier"],
        help="select the classifier to train on",
    )

    parser.add_argument(
        "-lhd",
        "--linear-hidden-dim",
        default=LINEAR_HIDDEN_DIM,
        help="Freeze Embeddings of Model",
        type=int,
    )

    args = parser.parse_args()

    seed_all(args.seed)
    logger.debug(args)
    logger.debug("Custom seed set with: {}".format(args.seed))

    logger.info("Loading Dataset")

    dataset = GrammarDasetAnswerKey.get_iterators(args.batch_size)

    logger.info("Dataset Loaded Successfully")

    if args.model_location:
        model = torch.load(args.model_location)
    else:
        model = initialize_new_model(
            args.model,
            dataset,
            args.embedding_dim,
            args.hidden_dim,
            args.n_layers,
            args.bidirectional,
            args.dropout,
            args.freeze_embeddings,
            args.linear_hidden_dim,
        )

    criterion = nn.BCEWithLogitsLoss()
    optimizer = optim.Adam(
        model.parameters(), lr=LR, weight_decay=args.l2_regularization
    )

    model = model.to(device)
    criterion = criterion.to(device)

    logger.info(model)

    if not os.path.exists(TRAINED_CLASSIFIER_FOLDER):
        os.mkdir(TRAINED_CLASSIFIER_FOLDER)

    best_test_loss = float("inf")

    for epoch in range(int(args.epochs)):

        start_time = time.time()
        train_loss, train_acc = train(
            model, dataset.train_iterator, optimizer, criterion
        )
        test_loss, test_acc = evaluate(model, dataset.test_iterator, criterion)

        end_time = time.time()

        epoch_mins, epoch_secs = epoch_time(start_time, end_time)

        if test_loss < best_test_loss:
            best_test_loss = test_loss
            torch.save(
                model,
                os.path.join(TRAINED_CLASSIFIER_FOLDER, TRAINED_CLASSIFIER_RNNHIDDEN),
            )

        print(f"Epoch: {epoch+1:02} | Epoch Time: {epoch_mins}m {epoch_secs}s")
        print(f"\tTrain Loss: {train_loss:.3f} | Train Acc: {train_acc*100:.2f}%")
        print(f"\t Val. Loss: {test_loss:.3f} |  Val. Acc: {test_acc*100:.2f}%")


Overwriting train.py


### Utils


In [18]:
%%writefile utility.py
"""
Utility methods to be used for training and dataloading purposes
"""

import time

import spacy
import torch

nlp = spacy.load("en")


def isin(ar1, ar2):
    """
    Takes two torch tensors as input and returns 
    """
    return (ar1[..., None] == ar2).any(-1)


def epoch_time(start_time, end_time):
    elapsed_time = end_time - start_time
    elapsed_mins = int(elapsed_time / 60)
    elapsed_secs = int(elapsed_time - (elapsed_mins * 60))
    return elapsed_mins, elapsed_secs


def tokenizer(text):
    results = []
    text = text.replace("<blank>", " BLANKK ")
    text = text.replace("<slash>", " SLASHH ")
    text = text.replace("<Q>", " QSTARTIT ")
    text = text.replace("</Q>", " QENDIT ")
    text = text.replace("<K>", " KSTARTIT ")
    text = text.replace("</K>", " KENDIT ")
    text = text.replace("<A>", " ASTARTIT ")
    text = text.replace("</A>", " AENDIT ")
    for token in nlp(text):
        if token.text == "BLANKK":
            results.append("<blank>")
        elif token.text == "SLASHH":
            results.append("<slash>")
        elif token.text == "QSTARTIT":
            results.append("<Q>")
        elif token.text == "QENDIT":
            results.append("</Q>")
        elif token.text == "KSTARTIT":
            results.append("<K>")
        elif token.text == "KENDIT":
            results.append("</K>")
        elif token.text == "ASTARTIT":
            results.append("<A>")
        elif token.text == "AENDIT":
            results.append("</A>")
        else:
            results.append(token.text)

    return results


def categorical_accuracy(preds, y):
    """
    Returns accuracy per batch
    """
    max_preds = preds.argmax(dim=1, keepdim=True)
    correct = max_preds.squeeze(1).eq(y)
    return correct.sum() / torch.FloatTensor([y.shape[0]])


def binary_accuracy(preds, y, mask):
    """
    Returns accuracy per batch, i.e. if you get 8/10 right, this returns 0.8, NOT 8
    """

    rounded_preds = torch.round(torch.sigmoid(preds))
    correct = ((rounded_preds == y) * mask).float()  # convert into float for division
    acc = correct.sum() / mask.sum()
    return acc


Overwriting utility.py


# Testing ground

In [0]:
import torch
import numpy as np

In [0]:
a = torch.Tensor([1,2 ,3, 4, 5])
b = torch.Tensor([2, 4])

In [16]:
(a[..., None] == b).any(-1)

tensor([False,  True, False,  True, False])

In [0]:
a = torch.ones([4, 10])
b = torch.zeros([4, 2])

In [0]:
a[0][4] = 3
a[0][7] = 5
b[0][0] = 3
b[0][1] = 5

In [92]:
a[0], b[0]

(tensor([1., 1., 1., 1., 3., 5., 1., 1., 1., 1.]), tensor([3., 5.]))

In [51]:
test1 = torch.tensor([1, 2, 3])
test2 = torch.tensor([2])
isin(test1 , test2)
(test1[... , None] == test2)

tensor([[1],
        [2],
        [3]])

In [96]:
a[0], b[0]

(tensor([1., 1., 1., 1., 3., 5., 1., 5., 1., 1.]), tensor([3., 5.]))

In [0]:
x = np.isin(a.numpy(), b.numpy())

In [99]:
np.where(x, 1, 0)

array([[0, 0, 0, 0, 1, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])